/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/views/About.vue')['default']
    Accounts: typeof import('./src/components/views/Accounts.vue')['default']
    AddTransactionModal: typeof import('./src/components/right/AddTransactionModal.vue')['default']
    AssetPieChart: typeof import('./src/components/left/AssetPieChart.vue')['default']
    BudgetSettings: typeof import('./src/components/views/BudgetSettings.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ExpenseTrendChart: typeof import('./src/components/charts/ExpenseTrendChart.vue')['default']
    GlobalFooter: typeof import('./src/components/footer/GlobalFooter.vue')['default']
    Home: typeof import('./src/components/views/Home.vue')['default']
    ImportModal: typeof import('./src/components/right/ImportModal.vue')['default']
    LeftPanel: typeof import('./src/components/left/LeftPanel.vue')['default']
    Log: typeof import('./src/components/register/Log.vue')['default']
    Login: typeof import('./src/components/register/Login.vue')['default']
    MonthlyComparisonChart: typeof import('./src/components/charts/MonthlyComparisonChart.vue')['default']
    ProfilePlaceholder: typeof import('./src/components/views/ProfilePlaceholder.vue')['default']
    Reg: typeof import('./src/components/register/Reg.vue')['default']
    RightPanel: typeof import('./src/components/right/RightPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Statistics: typeof import('./src/components/views/Statistics.vue')['default']
    TransactionDetail: typeof import('./src/components/views/TransactionDetail.vue')['default']
    TransactionList: typeof import('./src/components/middle/TransactionList.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
